spring:
  rabbitmq:
    host: 192.168.125.128
    username: dxh
    password: dxh
    virtual-host: /dxh
    template:
      exchange: GMALL.ITEM.EXCHANGE   #交换机名称,发送消息到这个交换机的名称
    publisher-confirms: true